configurable watch namespaces
grafana/k6-operator pull request #225
Opened 2023-05-04 08:26 UTC by dkhachyan

2023-05-05 15:25 UTC, yorugac commented
As mentioned in [PR 217](https://github.com/grafana/k6-operator/pull/217#discussion_r1183740038), this would be a breaking change for existing setups: that's why I suggested opening an issue instead. If namespace is to be configured, it must be optional, not mandatory by default.

2023-05-05 15:31 UTC, dkhachyan commented
It's not a breaking change. If WATCH_NAMESPACE is not set operator will watch all namespaces

2023-05-15 13:52 UTC, yorugac requested changes
Looking at this PR with fresh eyes, I think its possible to have an optional namespace if we keep just the changes in `main.go` and remove changes in manifest. I.e. by default `WATCH_NAMESPACE` is empty and the operator is watching everything. But if a user sets `WATCH_NAMESPACE` env var for the operator, only that namespace will be watched. Could you please adjust your PR accordingly?

2023-05-15 13:52 UTC, yorugac commented on config/manager/manager.yaml
> +                  fieldPath: metadata.namespace
Please remove changes in this file.

2023-05-16 11:45 UTC, dkhachyan commented on config/manager/manager.yaml
> +                  fieldPath: metadata.namespace
done

2023-05-23 17:34 UTC, yorugac commented on config/manager/manager.yaml
> +                  fieldPath: metadata.namespace
Great; thanks for the update!

2023-05-23 17:39 UTC, yorugac approved these changes

2023-05-23 17:41 UTC, merged

2024-08-19 12:07 UTC, artem-zherdiev-ingio commented
Hey, any documentation on how to use it?

2024-08-20 15:05 UTC, yorugac commented
Documentation is here:
https://grafana.com/docs/k6/latest/set-up/set-up-distributed-k6/install-k6-operator/#watch-namespace