feat: differentiate between Runner and Initializer initContainers
grafana/k6-operator pull request #379
Opened 2024-02-29 10:16 UTC by FloGro3

Fixes [296](https://github.com/grafana/k6-operator/issues/296)

Enables you to have separate initContainers for the initializer and runner pod. 

Was tested successfully in own K8 environment (only the initializer pod was configured to have initContainers):
![image](https://github.com/grafana/k6-operator/assets/93530403/6f83b9e3-be1d-4fc3-8289-2d712223cc53)

Config looks like this:
```yaml
initializer:
    ...
    {{- if .Values.executor.script.volumeClaim }}
    initContainers:
      - image: {{ tpl $.Values.docker.registry $ }}/{{ tpl $.Values.image.name $ }}:{{ tpl $.Values.image.tag $ }}
        {{- if .Values.image.command }}
        command: [ "sh", "-c", {{ .Values.image.command }} ]
        {{- else }}
          {{- with (index .Values.mount.pvcs 0) }}
        command: [ "sh", "-c", "cp -r /home/* {{ .path }};" ]
          {{- end }}
        {{- end }}
    {{- end }}
```

2024-02-29 11:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6-operator?pullRequest=379) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6-operator?pullRequest=379) before we can accept your contribution.<br/><hr/>**florian-tobias.grotke@capgemini.com** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6-operator?pullRequest=379) it.</sub>

2024-03-01 16:59 UTC, yorugac requested changes
@FloGro3, thanks for working on this! Could you please add an example for this case to `config/samples`?

2024-03-04 14:40 UTC, FloGro3 commented
@yorugac Sure, I've added a small example.

2024-03-18 12:56 UTC, yorugac approved these changes
Apologies for such a delay, @FloGro3!
LGTM, merging in now. Thanks again for working on this :raised_hands:

2024-03-18 12:56 UTC, merged