fix: treat Failed as error during test init (PullRequest 291 continued)
grafana/k6-operator pull request #401
Opened 2024-05-10 12:08 UTC by irumaru

PullRequest 291 has been out of date, and I believe that more time has passed and merging has become more difficult, so I have reworked the PR.
The changes are basically the same as in PullRequest 291, with a few modifications based on comments.

https://github.com/grafana/k6-operator/pull/291

Thanks to JorTurFer and yorugac

2024-05-10 12:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6-operator?pullRequest=401) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6-operator?pullRequest=401) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6-operator?pullRequest=401) it.</sub>

2024-05-17 05:58 UTC, irumaru commented
Hello.
When do you plan to review this?
@yorugac

2024-05-20 20:35 UTC, yorugac requested changes
Hi @irumaru, thanks for picking this up :raised_hands: Sorry for the delay.

I think this change is fine. I'll test it a bit in coming days and if nothing comes up, I'll merge it in. Meanwhile, there's a small verbosity request for logs - please see the comment.

2024-05-20 20:35 UTC, yorugac commented on controllers/common.go
> +		returnErr = errors.New("init job has failed")
```suggestion
		returnErr = errors.New("initalizer job has failed")
```

2024-05-21 04:04 UTC, irumaru commented
Thank you for your request.
This is easier to understand and will be changed!

2024-05-23 14:46 UTC, yorugac approved these changes
LGTM! Thanks again @irumaru.

2024-05-23 14:47 UTC, merged