generate helm values schema
grafana/k6-operator pull request #432
Opened 2024-07-27 11:19 UTC by petar-cvit

closes #431

Adds initial `schema.values.json` to the chart and extends `helm-release` with a step that generates and commits the schema.

Also, adds a new Makefile target to generate the schema using [github.com/dadav/helm-schema](github.com/dadav/helm-schema).

2024-07-27 11:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6-operator?pullRequest=432) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6-operator?pullRequest=432) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6-operator?pullRequest=432) it.</sub>

2024-07-30 16:05 UTC, yorugac requested changes
Hi @petar-cvit, thank you for the PR!

The schema makes sense and looks reasonable, IMHO, except for one field marked as required: please see my comment.

The CI probably won't work out-of-the-box :sweat_smile: Esp. tied to the release. I'll need to test it from the main branch and probably tinker with it anyway, but thanks for the base to build on :raised_hands:

2024-07-30 16:06 UTC, yorugac commented
Also, @petar-cvit, please sign the CLA!

2024-08-02 11:31 UTC, petar-cvit commented on charts/k6-operator/values.schema.json
> +            "pullSecrets"
All fields are required by default. I added the `required: false` annotation to mark it as not required

2024-08-06 11:42 UTC, yorugac commented
@petar-cvit, thanks for the updates! I don't have any other change requests except: CLA is marked as not signed?
![image](https://github.com/user-attachments/assets/c6883107-7c41-43ed-b4f4-658c7f65b56c)

2024-08-09 08:39 UTC, petar-cvit commented
@yorugac, sorry for the delay. CLA signed

2024-08-12 12:51 UTC, yorugac approved these changes
LGTM! Thank you @petar-cvit :slightly_smiling_face:

2024-08-12 12:52 UTC, merged