Fixing manager.env schema and added manager.envFrom
grafana/k6-operator pull request #474
Opened 2024-10-04 17:19 UTC by julian-perge

With 3.9.0, the `values.schema.json` is created incorrectly from the `values.yaml`, therefore not allowing any extra env values from `manager.env` to be placed in there since it's requiring an object, but `env` is supposed to be an array of objects.

2024-10-04 17:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6-operator?pullRequest=474) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6-operator?pullRequest=474) before we can accept your contribution.<br/><hr/>**Julian Perge** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6-operator?pullRequest=474) it.</sub>

2024-10-06 19:46 UTC, yorugac commented
Hi @julian-perge, thanks for the PR. 
According to the https://github.com/grafana/k6-operator/issues/471, there is probably a whole list of values that should be changed in the schema, if not all of them. If you'd like to work on that issue, https://github.com/grafana/k6-operator/issues/471, you're welcome to, but the schema overall should be fixed, not just a part of it.
Also, just in case, signing CLA is mandatory for this repo :slightly_smiling_face:

2024-10-07 23:07 UTC, julian-perge commented
> Hi @julian-perge, thanks for the PR. According to the #471, there is probably a whole list of values that should be changed in the schema, if not all of them. If you'd like to work on that issue, #471, you're welcome to, but the schema overall should be fixed, not just a part of it. Also, just in case, signing CLA is mandatory for this repo 🙂

Thanks for the issue link, and I signed the CLA, but had my signing keys messed up. Should be fixed now.

2024-10-07 23:41 UTC, julian-perge commented
@yorugac Updated PR to include the rest of the schema fixes.

2024-10-28 20:04 UTC, yorugac requested changes
Hi @julian-perge, apologies for the delay! I've finally tested this: it seems that `tolerations` should also be changed to `array` - please see my comment below.
That's the only request from me: the rest seems to be working, AFAIS :raised_hands: Would you be able to update that part?

2024-10-28 20:04 UTC, yorugac commented on charts/k6-operator/values.yaml
>  # type: object
```suggestion
# type: array
```
I'm getting the following error now:
```
- tolerations: Invalid type. Expected: object, given: array
```
And tolerations are normally defined as an array:
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

2024-10-31 12:22 UTC, yorugac commented on charts/k6-operator/values.yaml
>  # type: object
It appears this change request was done in a new PR by another contributor over here:
https://github.com/grafana/k6-operator/pull/481/files

2024-10-31 12:29 UTC, yorugac approved these changes
@julian-perge, I'll be merging your PR as is now, and merge the fix for tolerations from https://github.com/grafana/k6-operator/pull/481. I hope that's alright with you!

2024-10-31 12:30 UTC, merged