Tolerations is an array and has been updated as such in the values.schema.json
grafana/k6-operator pull request #481
Opened 2024-10-29 14:18 UTC by ollie-kane-CB

Simple pull request to fix a typo.  Without this, you must use --skip-schema-validation to install the chart that uses tolerations as they're not object values; they're an array of objects.

The sample values in this project wouldn't pass validation.

2024-10-29 14:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6-operator?pullRequest=481) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6-operator?pullRequest=481) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6-operator?pullRequest=481) it.</sub>

2024-10-31 12:27 UTC, yorugac commented
Thanks for the PR, @ollie-kane-CB! I believe this is the same change request I've asked in https://github.com/grafana/k6-operator/pull/474 :slightly_smiling_face:

2024-10-31 12:40 UTC, yorugac commented on charts/k6-operator/values.yaml
>  # type: object
```suggestion
# type: array
```

2024-10-31 12:41 UTC, yorugac requested changes
@ollie-kane-CB, there is a one-line fix that should be added; please see my comment above. Also, could you please rebase your PR against the new main branch?

2024-10-31 13:08 UTC, closed without merging

2024-10-31 13:55 UTC, yorugac commented
@ollie-kane-CB, it appears you've closed the PR: is it intentional?

2024-10-31 15:57 UTC, ollie-kane-CB commented
I was fumbling with github's idiosyncracies (i'm a gitlabber, so it's like a parallel universe) and was struggling to rebase.  I closed because I don't know when I'll get around to fixing and didn't want to create noise.  I'll re-open in a few days to resolve.

2024-11-01 13:13 UTC, yorugac commented
@ollie-kane-CB, thanks for the clarification! FYI, I've fixed tolerations separately here: https://github.com/grafana/k6-operator/pull/484 in order to make a Helm release sooner. This schema bug has already remained un-fixed for way too long, IMO, so I'd like to rectify that ASAP.

Just in case, you're very welcome to pick up some other issue if you'd like to! :slightly_smiling_face: