feat: allow service without authproxy
grafana/k6-operator pull request #504
Opened 2024-12-10 09:33 UTC by afreyermuth98

I want to be able to access the service without using the authproxy.
Moreover I added the way to put some custom labels and annotations on it

2024-12-20 11:42 UTC, yorugac commented
@afreyermuth98, thanks for the PR! We don't have an issue for this yet, so could you please describe more precisely the use cases you're facing?

FYI, there are rather large structural changes in manifests happening as part of #235, and authentication and metrics will be impacted as well. So this PR can be considered only after that work is done. Given the holidays, that'll probably be in the next year. Meanwhile, if you have the time to consider how your proposal will fit in into the new structure and updated manifests, I'd appreciate it greatly! (ref. PR: https://github.com/grafana/k6-operator/pull/512, also https://github.com/kubernetes-sigs/kubebuilder/discussions/3907)

2025-01-06 08:52 UTC, afreyermuth98 commented
Hello @yorugac ! Thanks for this answer :)
My needs are pretty simple : 
I have an otel collector that is scraping my pods / service depending on their annotations and I do not (want to) set auth-proxy on my k6-operator setup. But the service is created only if auth-proxy is enabled so it blocks me.
With my PR, I can force to have a service (with custom annotations) to get it scraped and collect the metrics without having to set the auth-proxy. 
Do not hesitate to reach me again if it's not clear / if something is needed :)

2025-04-17 09:35 UTC, afreyermuth98 commented
@yorugac up ? :)

2025-04-17 16:13 UTC, yorugac commented
Hi @afreyermuth98, thanks for the ping! Apologies, this PR totally slipped from my radar :disappointed: 

Just for the record: the refactoring work in https://github.com/grafana/k6-operator/issues/235 has been postponed due to other, internal priorities. I'd have preferred to do that one instead, as it totally removes the auth proxy, IIRC. So once it is removed from manifests, we can remove it from the chart too. But yeah, we have what we have; let me review properly!

cc @EladAviczer, I think it's the same bug you pointed out it in #544 - please check.

2025-04-17 16:31 UTC, yorugac requested changes
This is pretty simple and overall LGTM! I've left a couple of small comments and questions -- please see below.

Also, just in case, schema can be generated with `make helm-schema` :slightly_smiling_face:

2025-04-17 16:31 UTC, yorugac commented on charts/k6-operator/values.yaml
> +  # service.enabled -- enables the k6 service (default: false)
```suggestion
  # service.enabled -- enables the k6-operator service (default: false)
```

2025-04-17 16:31 UTC, yorugac commented on charts/k6-operator/values.yaml
> +
Btw, can you please describe why service would need these separately defined?
I think you mentioned it in description of your use case too, that you need annotations for scrapers. Which makes sense, but why can't they be the same as for deployment?

2025-04-17 16:31 UTC, yorugac commented on charts/k6-operator/values.yaml
> +  enabled: false
```suggestion
  enabled: true
```
Current default state for Service is actually true. Let's not change the default without a reason.

2025-04-17 17:29 UTC, EladAviczer commented
> cc @EladAviczer, I think it's the same bug you pointed out it in #544 - please check.

@yorugac Yesss :)

2025-04-28 08:26 UTC, afreyermuth98 commented
@yorugac Review done !
I want to be separately adressed because I don't want to have the scraping annotation on the service AND on the pods, it would create a duplicate of scraping

2025-05-06 10:25 UTC, yorugac approved these changes
Thank you for the update, @afreyermuth98! LGTM :+1:

2025-05-06 10:25 UTC, merged