Feature moving to Helm from Kustomize
grafana/k6-operator pull request #98
Opened 2022-02-02 12:18 UTC by knmsk

Hi everyone,
I moved most of things out of kustomize to helm chart. I had some problems trying to set-up the MutationWebhookConfiguration and ValidatingWebhookConfiguration, if anyone can help with this i will be glad.
Also, i added some liveness and readiness probe configuration on the controller-runtime in case someone will need it too due to requirements of the company cluster. 

Closes #92

2022-02-18 09:03 UTC, AbdelrhmanHamouda commented
Hello @knmsk,
Any plans to have this as part of the 0.0.7 release?

2022-02-21 16:17 UTC, knmsk commented
probably after the discussion of issue #92

2022-05-11 10:41 UTC, guillermotti commented
Hi @knmsk!!

Do you know when this PR will be merged? I created a custom Helm Chart meanwhile but would be great to use the official one.

Thanks for your work! Amazing ❤️

2022-05-15 15:57 UTC, knmsk commented
I thought about having a helm and a operator format to use, so probably i'll undo the operator removal and ask @yorugac to review it

2022-05-15 15:58 UTC, knmsk commented
> Hi @knmsk!!
> 
> Do you know when this PR will be merged? I created a custom Helm Chart meanwhile but would be great to use the official one.
> 
> Thanks for your work! Amazing ❤️ 

@guillermotti i thought about having a helm and a operator format to use, so probably i'll undo the operator removal and ask @yorugac to review it. But at my company we already use this PR to deploy our k6-operator

2022-06-28 12:20 UTC, phlegx commented
Hi there! What is the status of this Pull Request. We would need this Helm way as well!

2022-07-04 13:20 UTC, yorugac commented
Hi @phlegx, this PR is planned to be merged for the next big release, v0.0.8. The release will not be earlier than August / September, but hopefully, Helm support itself will be merged before that.

2022-07-20 06:52 UTC, ksemele commented
@knmsk FYI
I already signed CLA, all under control, but need recheck :)

![image](https://user-images.githubusercontent.com/54932673/179915976-032c5d17-7d87-476d-8000-c57087fa91bb.png)

2022-09-19 12:02 UTC, yulianovikova commented
Hi!
Is this PR still planned for the v0.0.8 release? As far as I can see, 0.0.8rc1 does not include this feature yet :( Maybe you could also tell me when Helm support is planned to be released?
We are looking forward to this feature to be merged. Thank you!

2022-09-23 15:36 UTC, yorugac commented
Hi @yulianovikova,

Unlike k6, k6-operator does not have any set schedule around releases. The reason is simple: the time resources allocated for it are limited and workload is impacted by external requests and now major issue #138. So previous estimation became invalid. I still would like to add Helm first but cannot say the dates at the moment. TBH, I'm not happy about this either. I'll try to see if anything can be improved and will update again if / when there are changes.

For now, I added next pre-release v0.0.8-rc3 (the rc2 has a CI issue), to have a new proper tagged image.

2022-12-06 14:35 UTC, Dariusch commented on charts/templates/prometheus/serviceMonitor.yaml
> +  namespace: system
quick note: you missed this one.
This should either be `namespace: {{- include "operator.namespace" . }}` or configurable

2023-02-16 19:59 UTC, mclite reviewed
Any updates on this? I'd like to start using it my company. Also can you make sure the Helm chart gets added to AWS EKS Blueprints

2023-03-11 16:25 UTC, knmsk commented
I've updated the code with the suggestions that @StianOvrevage and @Dariusch mentioned

> while we are at it:
> Is the prometheus ServiceMontitor really necessary? Afaik prometheus metrics are pushed to the [remote write gateway](https://k6.io/docs/cloud/integrations/prometheus-remote-write/) and not scraped (via a ServiceMonitor).
@Dariusch I think it isn't necessary anymore, can @yorugac confirm this?

2023-03-31 16:39 UTC, zalbiraw commented
Any updates? :)

2023-04-11 09:21 UTC, chrisduong commented
I had used this chart, and haven't found major issues. Please merge asap 🙂

2023-04-19 15:08 UTC, vazhnov commented
I've successfully installed the K6 operator from Helm chart with the freshest code changes.
I think it is good time to merge the changes. Any improvements can be done in new merge requests.

2023-04-19 23:30 UTC, knmsk commented
Hey @danielfigueiredo can you also sign the licence/cla?
I want to get this PR ready, so when a Maintain wants to merge it, it's ok

2023-04-21 20:11 UTC, danielfigueiredo commented
> Hey @danielfigueiredo can you also sign the licence/cla? I want to get this PR ready, so when a Maintain wants to merge it, it's ok

Thanks for the prompt @knmsk , CLA signed!

2023-05-04 01:54 UTC, JeffCT0216 commented
Thanks @knmsk for working on this! 
I'm currently waiting for this to be merge to deploy using helm, is there an estimate on when this will be merged?

2023-05-19 09:18 UTC, vazhnov commented
Guys, what else do we need to merge the code?

2023-05-22 08:58 UTC, vr commented
this needs to be updated because some permissions and CRDs are not up2date

2023-07-11 04:24 UTC, finitelife commented
I can't get this branch working.

k8s: v1.25.9

1. leader election not working

modified charts/templates/clusterRole.yaml:
```
kind: ClusterRole
# ...
rules:
- {apiGroups: [coordination.k8s.io],resources: [leases],verbs: [create,get,update,patch]}
# ...
```

2. process stops at initializer job success (no tests are actually run)

2023-07-19 10:42 UTC, Nerja commented
@knmsk opened a PR with some updates: https://github.com/knmsk/k6-operator/pull/4. Currently testing it out, and so far I have not seen any issues.

2023-08-01 07:15 UTC, aaguilartablada commented
hello. when do you think this PR will be merged?

2023-08-01 19:26 UTC, Nerja commented
Reached out to @knmsk and asked him to have a look at my PR. He told me that he will have a look when he gets back from his vacation.

2023-08-16 19:36 UTC, Nerja commented
@yorugac any chance that you could take a look at the updates?

2023-08-17 11:53 UTC, yorugac commented
Hello! Just as a heads-up for everyone watching this issue / PR: it was prioritized internally at last :joy: 

My apologies for the Helm support taking so long: we really had other priorities and limited maintenance time. Not to say it's all perfect now, but we had major improvements in [idempotence problem](https://github.com/grafana/k6-operator/issues/138) and added support for [bundle installation](https://github.com/grafana/k6-operator/issues/4) so now its finally time to look into adding Helm support as well.

Thank you, Rogerio and everyone contributing, for your patience. @knmsk, if you could please rebase the branch some time, it'd be great :slightly_smiling_face:

Also, it seems that not all contributors here have signed the CLA: please do so! It'll not be possible to merge it otherwise.

2023-08-17 13:41 UTC, vazhnov commented
> Also, it seems that not all contributors here have signed the CLA

@yorugac, could you please check who exactly haven't signed the CLA? Because this issue is ongoing for months and I'm afraid it will block the whole merge request to be merged.

2023-08-17 14:11 UTC, yorugac commented
@vazhnov It's public info over here: https://github.com/grafana/k6-operator/pull/98#issuecomment-1087674948

cc @danielfigueiredo I assume? Not sure why it says "not Github user" :confused: There's a "recheck" link in the comment above that you should be able to use to help trigger CLA check yourself, just in case.

2023-08-17 17:02 UTC, danielfigueiredo commented
This is the same issue I had before
The recheck button takes me to github.com home page
Clicking on the agreement link says I already signed and all fields are greyed out

See video as proof:

https://github.com/grafana/k6-operator/assets/6464911/52c30764-be91-4c8c-9e07-95dfe6769603

2023-08-17 18:22 UTC, yorugac commented
@danielfigueiredo, this is just a guess but could it be because of different emails? Your commit goes under `*@*simple.com` but here it's `@gmail.com`.

2023-08-17 19:35 UTC, danielfigueiredo commented
Oh damn, that's going to be a problem. I can't re-write history to `rebase -i` and amend using the correct email because I can't make changes to the fork
I fixed the email on the history on my fork, and when I get a PR open against @knmsk's fork the diff goes crazy. The diff is the same, but I think git sees them as diff since I had to re-commit (via rebase -i) everything from my commit forwards. [See diff](https://github.com/knmsk/k6-operator/compare/feat/helm-chart...danielfigueiredo:k6-operator:feat/helm-chart-email-fix)

Afaik I only have to provide the last commit hash before mine when `rebase -i`, but there were 2 merge commits and so they extrapolated to a bunch of commits. 

@knmsk if you want to just amend the commit under your name I'm fine with that, I can't think of any simple way of fixing this. Open to suggestions

2023-08-18 14:15 UTC, yorugac commented
It seems there was a somewhat similar case of CLA confusion over here:
https://github.com/grafana/mimir-prometheus/pull/269#issuecomment-1161148083

Apparently, making a "Co-authored-by" commit allowed to bypass the problem. Github docs [on such commits](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors). It's still strange but perhaps that could work here as well.
cc @danielfigueiredo @knmsk

2023-08-18 14:37 UTC, knmsk commented
Just to make sure that I got it, I need to make a commit with a manual co-authored-by @danielfigueiredo to bypass this problem, right?

2023-08-18 14:42 UTC, danielfigueiredo commented
Okay, @knmsk I just managed to fix it!
Ended up adding the other email to my github account temporarily so that w can bypass this issue
should be unblocked now
thanks @yorugac for all the help too

2023-08-18 15:14 UTC, knmsk commented
Sorry, had to do a rebase since I've got some merge problems that I usually not run into 😢

2023-08-22 09:09 UTC, yorugac requested changes
@knmsk, this is an amazingly large work, thanks! :smile: 

I've gone through the main points: most of the change requests are small and should be relatively quick to fix. Quite a few of them seem to be just leftovers because of rebasing lots of commits at once.

Other than those leftovers, most noticeable change request is around names: see the comment in `_helpers.tpl`. As it is, the installation doesn't work for me ATM.

There are also a couple of questions I'd like to clarify with you, e.g. in `values.yaml` and `Makefile`.

Btw, thank you for including CI workflows! One of the main blockers for merging this was the additional effort required to maintain the chart: working CI would help with that :+1: I hope they'll work out-of-the-box.

2023-08-24 21:59 UTC, knmsk commented on Makefile
> +	go get sigs.k8s.io/kustomize/kustomize/v3@v3.5.4 ;\
Sorry missed this one out, fixing!

2023-08-24 22:16 UTC, knmsk commented on Makefile
> +bundle-helm: manifests
Yeah, it is a misconfig, removed from the file

2023-08-24 22:17 UTC, knmsk commented on Makefile
> +	operator-sdk bundle validate ./bundle
Yeah fixed

2023-08-24 22:30 UTC, knmsk commented on charts/values.yaml
> +controlPlane: "controller-manager"
I thought that it could be used by another operator, but checking now it doesn't make sense, removing this from the values.yaml

2023-08-24 23:07 UTC, knmsk commented on charts/templates/_helpers.tpl
> +{{- define "k6-operator.fullname" -}}
Fixed the namespace name...`k6-operator.namespace` on _helpers.tpl will be the default namespace name

2023-08-24 23:53 UTC, knmsk commented on charts/templates/_helpers.tpl
> +{{- define "k6-operator.fullname" -}}
Applied the suggestions that you made. Can you give me more context about the PLZ?
I've synced with the default branch to be sure it's the same

2023-08-31 15:04 UTC, yorugac commented on charts/templates/_helpers.tpl
> +{{- define "k6-operator.fullname" -}}
Yes, seems to be working out-of-the-box now :tada: Thanks for the update :smile: 

> Can you give me more context about the PLZ?

PLZ is a new CRD I'm actively working on now. It's meant for k6 Cloud feature "PrivateLoadZone". Public docs for it are coming™. It's OK to just copy it at this point :+1: And it seems to work fine as well now, after your update.

I'll test a bit more and let you know if something comes up. Resolving this comment.

2023-09-01 12:05 UTC, yorugac requested changes
The changes are working as far as I checked :raised_hands: There will probably be small adjustments we'll have to do in the future but otherwise, it looks pretty neat!

@knmsk, I'm marking this as a change request because of `bundle/`: I'm not clear why it was added. We might return to it if we ever get to #3 but it shouldn't be required for Helm support, AFAIS. Could you please remove it?

A note for the future: each update of CRD(s) will need to be copy-pasted to the `charts/templates/crds` in order to be picked up by the next chart release.

2023-09-01 12:05 UTC, yorugac commented on charts/values.yaml
> +  # manager.env -- Environment variable to be passet to the controller
```suggestion
  # manager.env -- Environment variable to be passed to the controller
```
:sweat_smile:

2023-09-06 21:08 UTC, knmsk commented
@yorugac yeah, its not supposed to have a bundle folder commited at least

2023-09-13 08:07 UTC, yorugac approved these changes
LGTM! The scenarios I've tested work and the structure is straight-forward :+1:

Thank you again for the work and updates and esp. patience, @knmsk and everyone who helped :smile:

2023-09-13 08:52 UTC, merged